title: Visual Archive
author: RS
email: RS
description: A visual archive of the Roe-era abortion debate, 1970 to the present, including protest materials, logos, merchandise, and newspaper clippings intended for display in public space, created by individuals or collegiate, local, and national organizations. We analyze the terms and visual language used and reference key legislation, historical events, and organizations.

baseurl: "/docs"

social:
  twitter: joaomlneto
  facebook: joaomlneto
  instagram: joaomlneto
  github: joaomlneto
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
